---
title: "Clinical manifestations of primary CoQ deficiencies"

---

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-PR2Y8ZWQEW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PR2Y8ZWQEW');
</script>



<br>

Primary coenzyme Q (CoQ) deficiencies are clinically heterogeneous and currently lack a clear genotype-phenotype correlation. As a result, most cases are not diagnosed or are diagnosed too late. To help guide diagnosis and early treatment, here we analyse the associations between clinical manifestations (symptoms) and the different *COQ* genes that are reported in the literature.

In the tabs above you can search the frequency of clinical manifestations grouped by system ([Central Nervous System](CNS.html), [Peripheral Nervous System and sensory organs](PNS-Sensory.html), [Kidney](Kidney.html), [Heart](Heart.html), [Muscle](Muscle.html), [Lung](Lung.html), [Liver](Liver.html), [Other](Other.html)) and for each *COQ* gene.

Go to [Table](Table.html) to search the data by involved system, specific manifestation or *COQ* gene.

This tool is part of the review *PRIMARY COENZYME Q DEFICIENCIES: A LITERATURE REVIEW AND ONLINE PLATFORM OF CLINICAL FEATURES TO UNCOVER GENOTYPE-PHENOTYPE CORRELATIONS*, María Alcázar-Fabra, Francisco Rodríguez-Sánchez, Eva Trevisson & Gloria Brea-Calvo (2021), which you can read [here](https://authors.elsevier.com/c/1cmZm3AkHAWDtX){target="_blank"}.  

Last update: `r Sys.Date()`

